# Assignment 1: Transformations


TEAM-ID:   
TEAM-NAME:   
YOUR-ID:   
YOUR-NAME:    

(Although you work in groups, both the students have to submit to Moodle, hence there's name field above)

# Instructions
- Please check Moodle for "TEAM-ID" and "TEAM-NAME" fields above. Some of your names have been edited because of redundancy/simplicity. Instructions for submitting the assignment through GitHub Classrooms/Moodle has been uploaded on Moodle. Any clarifications will be made there itself.
- Code must be written in Python in Jupyter Notebooks. We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. See `./misc/installation` for detailed step-by-step instructions about the installation setup.
- Both the team members must submit the zip file.
- For this assignment, you will be using Open3D extensively. Refer to [Open3D Documentation](http://www.open3d.org/docs/release/): you can use the in-built methods and **unless explicitly mentioned**, don't need to code from scratch for this assignment. Make sure your code is modular since you will be reusing them for future assignments.
- Take a look at the entire assignment. The descriptive questions at the end might have a clue if you are stuck somewhere.
- Answer the descriptive questions in your own words with context & clarity. Do not just copy-paste from some Wikipedia page. You will be evaluated accordingly.
- Please call the visualization functions only when they are asked. They are asked explicitly at the end of every section.
- You could split the Jupyter Notebook cells where `TODO` is written, but please try to avoid splitting/changing the structure of other cells.

In [1]:
import open3d as o3d
import time
import copy
import numpy as np
from scipy.linalg import logm
from scipy.spatial.transform import Rotation as R
from scipy.optimize import fsolve

# 1. Getting started with Open3D
## 1.1 Converting RGBD image into Point Cloud


In your robotics journey, it is common to be given just the depth images along with camera parameters in a generic dataset and you'd want to build a 3D data representation out of it, for example, a point cloud. You will understand the math behind these concepts in detail during Vision classes, for now, you can use the in-built functions as a black box.
- Below are the given RGB and D images from SUN RGB-D dataset ([S.Song, CVPR 2015](https://rgbd.cs.princeton.edu/)). 
![low-res-RGBD.resized.png](./misc/low-res-RGBD.png)

- Read these two images `color.jpg` and `depth.png` given in current folder using Open3D. Convert it to a point cloud using the default camera parameters (`o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault`).
Then,
- Create a "world" frame $A$ and combine this (just use $+$ operator) with the above point cloud and save it as `scene.pcd`. Put it aside for now.
- Write a simple function `one_one` to visualize `scene.pcd`.

In [2]:
##############################################################################
# TODO: Do tasks described in 1.1                                            #
##############################################################################

# CONSTANTS
NUM_SAMPLES = 2000
INIT_FACTOR = 5

color_scene = o3d.io.read_image('color.jpg')
depth_scene = o3d.io.read_image('depth.png')

pinhole_camera_intrinsic = o3d.camera.PinholeCameraIntrinsic(o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault)

rgbd_scene = o3d.geometry.RGBDImage.create_from_sun_format(color_scene, depth_scene, convert_rgb_to_intensity=False)
pcd_scene = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_scene, pinhole_camera_intrinsic)
Rot = pcd_scene.get_rotation_matrix_from_zyx((0, 0, np.pi))
pcd_scene.rotate(Rot, center=(0, 0, 0))


#World Frame
frame_world = o3d.geometry.TriangleMesh.create_coordinate_frame()
frame_world = frame_world.sample_points_poisson_disk(number_of_points=NUM_SAMPLES, init_factor=INIT_FACTOR)
pcd_scene = pcd_scene + frame_world

o3d.io.write_point_cloud('scene.pcd', pcd_scene)

def one_one(pcd):
    o3d.visualization.draw_geometries([pcd])
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################

### Question for 1.1

- In the next code cell, call the function `one_one` here showing `scene.pcd`.

In [3]:
#uncomment the following and add input parameters if any
pcd_scene = o3d.io.read_point_cloud('scene.pcd')
one_one(pcd_scene)

# 2. Rotations, Euler angles and Gimbal Lock

## 2.1 Rotating an object

The objective here is to roughly simulate an object moving on a ground.

- Generate a cube at some point on the ground and create another frame $B$ at the center of this object. Combine these both as a single point cloud `cube.pcd`. (You can pick a point on the ground by using the `get_picked_points` method of the class `open3d.visualization.VisualizerWithEditing`.)
- Now read both the point clouds `scene.pcd` and `cube.pcd` in a script. Whatever tasks you do below are on the object `cube.pcd` (along with the axes $B$) with `scene.pcd` in the background (static).
- Given a sequence of **ZYX Euler** angles $[30^{\circ}, 90^{\circ}, 45^{\circ}]$, generate the rotation. In our case, our object (with its respective axis) undergoes rotation with the background being fixed (with its respective axis).
- Note: Throughout this assignment, we will be using the standard **ZYX** Euler angle convention.
- Write a function `two_one` to show the above by **animation** (cube rotating along each axis one by one).
    - *Hint: Use Open3D's non-blocking visualization and discretize the rotation to simulate the animation. For example, if you want to rotate by $30^{\circ}$ around a particular axis, do in increments of $5^{\circ}$ 6 times to make it look like an animation.*

In [3]:
##############################################################################
# TODO: Do tasks described in 2.1                                            #
##############################################################################

# CONSTANTS
CUBE_COLOR = [194/255, 122/255, 192/255]
CUBE_SIZE = 0.4
CUBE_CENTER = [-CUBE_SIZE/2 for i in range(3)]
FRAME_SIZE = 0.6
NUM_SAMPLES = 5000

# Create the cube
mesh_cube = o3d.geometry.TriangleMesh.create_box(width=CUBE_SIZE, height=CUBE_SIZE, depth=CUBE_SIZE)
mesh_cube.paint_uniform_color(CUBE_COLOR)

mesh_frame_cube = o3d.geometry.TriangleMesh.create_coordinate_frame(size=FRAME_SIZE, origin=CUBE_CENTER)
framed_cube = (mesh_cube + mesh_frame_cube).sample_points_poisson_disk(number_of_points = NUM_SAMPLES, init_factor=INIT_FACTOR)

o3d.io.write_point_cloud('cube.pcd', framed_cube)

scene = o3d.io.read_point_cloud('scene.pcd')
cube = o3d.io.read_point_cloud('cube.pcd')

In [4]:
def pick_points(pcd):
    print('Pick points using SHIFT + Left Click. After the point is picked a circle will be formed around that point. Press q to exit the window.')
    print('Press ENTER to begin.')
    input()
    vis = o3d.visualization.VisualizerWithEditing()
    vis.create_window()
    vis.add_geometry(pcd)
    vis.run()
    vis.destroy_window()
    points = vis.get_picked_points()
    if len(points) == 0:
        raise ValueError('No points chosen.')
    return [pcd.points[i] for i in points]

In [5]:
cube_corner = pick_points(scene)[0]
cube.translate(cube_corner)
o3d.visualization.draw_geometries([scene, cube])

##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################

Pick points using SHIFT + Left Click. After the point is picked a circle will be formed around that point. Press q to exit the window.
Press ENTER to begin.

[Open3D INFO] Picked point #237474 (0.08, 0.024, 0.025) to add in queue.


In [7]:
def two_one(scene_path,cube_path):
    scene = o3d.io.read_point_cloud(scene_path)
    cube = o3d.io.read_point_cloud(cube_path)
    cube.translate(cube_corner)
    vis = o3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(scene)
    vis.add_geometry(cube)
    val = (np.pi)/36
    
    ROA = cube.get_rotation_matrix_from_zyx((val,0,0))
    for i in range(0,6):
        cube.rotate(ROA, center = CUBE_CENTER)
        vis.update_geometry(cube)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.1)
    
    ROA = cube.get_rotation_matrix_from_zyx((val*6,0,0))
    ROB = cube.get_rotation_matrix_from_zyx((val*6,val,0))
    ROAT = ROA.transpose()
    RAB = np.matmul(ROB, ROAT)
    for i in range(0,18):
        cube.rotate(RAB, center = CUBE_CENTER)
        vis.update_geometry(cube)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.1)
    
    ROB = cube.get_rotation_matrix_from_zyx((val*6, val*18, 0))
    ROC = cube.get_rotation_matrix_from_zyx((val*6, val*18, val))
    ROBT = ROB.transpose()
    RBC = np.matmul(ROC, ROBT)
    for i in range(0,9):
        cube.rotate(RBC, center = CUBE_CENTER)
        vis.update_geometry(cube)
        vis.poll_events()
        vis.update_renderer()
        time.sleep(0.1)
        
    vis.destroy_window()

### Question for 2.1

- In the next code cell, call the function `two_one` here showing the animation described in section 2.1.

In [10]:
#uncomment the following and add input parameters if any
two_one('scene.pcd','cube.pcd')

## 2.2 Euler angle & Gimbal lock

Code the following yourself from scratch (Refer Craig book - Section: $Z-Y-X$ Euler angles - same conventions/notations followed).

- Case 1: Given the rotation matrix $M_{given}$ below, extract Euler angles $\alpha , \beta ,\gamma$. Convert it back to the rotation matrix $M_{recovered}$ from Euler angles.

    $$M(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0.26200263 & -0.19674724 & 0.944799 \\0.21984631 & 0.96542533 & 0.14007684 \\
    -0.93969262 & 0.17101007 & 0.29619813\end{array}\right] $$

    After coding it from scratch, check your calculations using `scipy.spatial.transform.Rotation`. (Mandatory)

- Case 2: Given the rotation matrix $N_{given}$, extract Euler angles, and convert back $N_{recovered}$.

    $$N(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0 & -0.173648178 &  0.984807753 \\0 & 0.984807753 & 0.173648178 \\
    -1 & 0 & 0\end{array}\right] $$

    Again use `scipy` and check its output. If `scipy` is showing any warnings on any of the above cases, explain it in "**Questions for 2.2**" (last question). Write code in the next cell.
    
- (Optional) Case 3: Do the above two for quaternion using scipy functions, i.e. given the rotation matrix, extract quaternion and convert back.

In [6]:
##############################################################################
# DON'T EDIT
M_given =  np.array([[0.26200263, -0.19674724, 0.944799],
                     [0.21984631, 0.96542533, 0.14007684],
                     [-0.93969262, 0.17101007, 0.29619813]])

N_given = np.array([[0,-0.173648178,0.984807753],
                    [0, 0.984807753, 0.173648178],
                    [-1, 0, 0]])

In [7]:
# TODO: Do tasks described in 2.2                                            #
##############################################################################

def euler_zyx_from_rotation(R):
    beta = np.arctan2(-R[2, 0], np.sqrt(R[0, 0] ** 2 + R[1, 0] ** 2))
    alpha = np.arctan2(R[1, 0]/np.cos(beta), R[0, 0]/np.cos(beta))
    gamma = np.arctan2(R[2, 1]/np.cos(beta), R[2, 2]/np.cos(beta))
    return (alpha, beta, gamma)

def rotation_from_euler_zyx(alpha, beta, gamma):
    R = np.zeros((3, 3), dtype='double')
    
    R[0, 0] = np.cos(alpha) * np.cos(beta)
    R[0, 1] = np.cos(alpha) * np.sin(beta) * np.sin(gamma) - np.sin(alpha) * np.cos(gamma)
    R[0, 2] = np.cos(alpha) * np.sin(beta) * np.cos(gamma) + np.sin(alpha) * np.sin(gamma)
    
    R[1, 0] = np.sin(alpha) * np.cos(beta)
    R[1, 1] = np.sin(alpha) * np.sin(beta) * np.sin(gamma) + np.cos(alpha) * np.cos(gamma)
    R[1, 2] = np.sin(alpha) * np.sin(beta) * np.cos(gamma) - np.cos(alpha) * np.sin(gamma)
    
    R[2, 0] = -np.sin(beta)
    R[2, 1] =  np.cos(beta) * np.sin(gamma)
    R[2, 2] =  np.cos(beta) * np.cos(gamma)
    
    return R

In [8]:
# Case 1

# Ours
print('Ours:')
euler_M = euler_zyx_from_rotation(M_given)
print('Euler angles (zyx): ', np.array(euler_M))
M_generated = rotation_from_euler_zyx(*euler_M)
print('Recovered rotation matrix:\n', M_generated)

# Scipy's
print('\nScipy\'s:')
bench = R.from_matrix(M_given)
print('Euler angles (zyx): ', bench.as_euler('ZYX'))
bench2 = R.from_euler('ZYX', bench.as_euler('ZYX'))
print('Recovered rotation matrix:\n', bench2.as_matrix())

Ours:
Euler angles (zyx):  [0.6981317  1.22173048 0.52359878]
Recovered rotation matrix:
 [[ 0.26200263 -0.19674724  0.944799  ]
 [ 0.21984631  0.96542534  0.14007684]
 [-0.93969262  0.17101007  0.29619813]]

Scipy's:
Euler angles (zyx):  [0.69813171 1.22173048 0.52359878]
Recovered rotation matrix:
 [[ 0.26200263 -0.19674724  0.944799  ]
 [ 0.21984631  0.96542534  0.14007684]
 [-0.93969262  0.17101007  0.29619813]]


In [9]:
# Case 2

# Ours
print('Ours:')
euler_N = euler_zyx_from_rotation(N_given)
print('Euler angles (zyx): ', np.array(euler_N))
N_generated = rotation_from_euler_zyx(*euler_N)
print('Recovered rotation matrix:\n', N_generated)

# Scipy's
print('\nScipy\'s:')
bench = R.from_matrix(N_given)
print('Euler angles (zyx): ', bench.as_euler('ZYX'))
bench2 = R.from_euler('ZYX', bench.as_euler('ZYX'))
print('Recovered rotation matrix:\n', bench2.as_matrix())

##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################

Ours:
Euler angles (zyx):  [0.         1.57079633 0.        ]
Recovered rotation matrix:
 [[ 6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17]]

Scipy's:
Euler angles (zyx):  [0.17453293 1.57079633 0.        ]
Recovered rotation matrix:
 [[ 1.66533454e-16 -1.73648178e-01  9.84807753e-01]
 [ 2.77555756e-17  9.84807753e-01  1.73648178e-01]
 [-1.00000000e+00  0.00000000e+00  1.66533454e-16]]


/home/kanish/Downloads/MobileRobotics/venv/lib/python3.6/site-packages/scipy/spatial/transform/rotation.py:133: UserWarning: Gimbal lock detected. Setting third angle to zero since it is not possible to uniquely determine all angles.
  warnings.warn("Gimbal lock detected. Setting third angle to zero since"


## Questions for 2.2
- Have you used `np.arctan` or an any equivalent `atan` function above? Why or why not?   
    * Ans: We have used `np.arctan2` to calculate the inverse tangents of the given values. As opposed to a single-argument inverse tangent function, `np.arctan2` takes in $x$ and $y$ values separately, and uses them to infer the quadrant of the angle, thus being able to output angles in the complete range $[-\pi, \pi)$. Single-argument inverse tangents functions lack information about the individual signs of $x$ and $y$ and hence can only return an angle within the *principal-value range* of $[-\frac{\pi}{2}, \frac{\pi}{2}).$ Because this would have restricted the output euler angles, this was avoided.

### For Case 1 above,
- What Euler angles  $\alpha , \beta ,\gamma$ did you get? Replace `my_array_case1` with your array.

In [10]:
# Uncomment and replace my_array_case1 with your array.
print("My Euler angles for case 1 are " + str(euler_M))

My Euler angles for case 1 are (0.6981317003487097, 1.2217304765297095, 0.5235987753730347)


  - Were you able to recover back your rotation matrix when you converted it from Euler angles? Why/why not? Replace `M_given` and `M_recovered` with your matrices below and explain "why/why not" after this code snippet.

In [11]:
# Uncomment and Replace M_given and M_recovered with your matrices below.
error = np.linalg.norm(logm(M_given @ M_generated.T))
print("For case 1, it is " + str(error<0.0001) + " I could recover the original matrix.")

For case 1, it is True I could recover the original matrix.


- Why/why not? Based on your observations here, is there any problem with Euler angle representation for Case 1? If yes, what is it?

    - Ans: The problem with Euler Angles is their inability to be directly used in computations and the loss of precision that occurs while performing the mathematical conversions. While Euler angles are more compact and also easier to visualise than rotation matrices, they cannot be used to compute frame or point rotations directly, making them not-so-useful for a computer.

### Repeat the above for Case 2.

In [12]:
# Uncomment and Replace N_given and N_recovered with your matrices below.
print("My Euler angles for case 2 are " + str(euler_N))
error = np.linalg.norm(logm(N_given @ N_generated.T))
print("For case 2, it is " + str(error<0.0001) + " I could recover the original matrix.")

My Euler angles for case 2 are (0.0, 1.5707963267948966, 0.0)
For case 2, it is False I could recover the original matrix.


* Why/why not? Based on your observations here, is there any problem with Euler angle representation for Case 2? If yes, what is it?

    * Ans: *your answer here.*
    
    
* Explain any more problems with Euler angle representation. Explain what you understand by Gimbal lock (concisely in your own words). You could revisit this question in the section 2.4.
    * Ans: *your answer here.*

- When you used `scipy.spatial.transform.Rotation` for the above 2 cases,
    - Have you used `zyx` above in `r.as_euler('')` argument? Why or why not? Explain the difference between extrinsic and instrinsic rotations with equivalent technical names from Craig book?
        * Ans: *your answer here.*
    - Has `scipy` shown any warnings on any of the above cases? If yes, explain it.
        * Ans: *your answer here.*
    - (Optional) For Case 3 above (quaternion) which you did using scipy, did you observe any problem with quaternion? Depending on your observations, which is better? Quaternion or Euler angles? And why?
         * Ans: *your answer here.*


## 2.3 Rotation matrix as an Operator
This question will help you in your understanding of [Rotator-transform (Vector-frame) equivalence](https://www.notion.so/saishubodh/Lecture-2-Transformations-11d69d8cef2d4cd195a98fa7d33224e1#f90ece4f5e374743bfed47e46a83ecfe).

![image.png](./misc/xyz-frame.png)
Consider the frame $XYZ$ in the above image. Say you have a vector $x_1=[0,\sqrt{3},0]$. Now you want to rotate it such that you end up at $x_2=[1,1,1]$ through a sequence of Euler angle rotations. Your goal is to find out those $\alpha, \beta \: \& \: \gamma$ ($ZYX$). We will follow this order whenever we refer to it below.

First, properly understand the so-called "Rotator-transform equivalence" to figure out what are the terms of rotation matrix. Then, put the math on paper and you will end up with a set of non-linear equations. Write the set of linear equations in LaTeX here:

$$ \textbf{Ans: Your set of equations here} $$
$$ \sqrt{3}\sin{\gamma} \cos{\beta} - 1 = 0 $$
$$ \sqrt{3}\cos{\alpha}\cos{\gamma} + \sqrt{3}\sin{\alpha}\sin{\beta}\sin{\gamma} - 1 = 0 $$
$$ -\sqrt{3}\sin{\alpha}\cos{\gamma} + \sqrt{3}\cos{\alpha}\sin{\beta}\sin{\gamma} - 1 = 0 $$

Solve these equations using `fsolve` from `scipy.optimize` as follows: (Come back and answer the following questions after coding it in the next block)
- `case1`: First, solve it with an initialization of (0,0,0). Check if your answer is correct using `np.isclose`.
    * What Euler angles did you get? Answer in $\alpha, \beta \: \& \: \gamma$ format:
        * Ans: *$a_1, b_1, c_1$ = [ -0.32906483356361393, -93.69048524053285, 0.74815097858118 ]* 
- `case2`: Now, forget about the solver for a moment: Can you visualize and think of sequence of rotations one by one to reach the final position (which is different than previous set of rotations)? Now, validate your answer by giving (your answer $\pm 5$) as initialization.
    * What Euler angles did you get? Answer in $\alpha, \beta \: \& \: \gamma$ format:
        * Ans: *$a_2, b_2, c_2$ = your answer here.*

In [17]:
##############################################################################
# DON'T EDIT
x_1 = np.array([0,np.sqrt(3),0])
x_2 = np.array([1,1,1])

In [57]:
##############################################################################
# TODO: Do tasks described in 2.3                                            #
#########a#####################################################################
# Replace "pass" statement with your code
def func(x):
    return [np.sqrt(3) * np.sin(x[2]) * np.cos(x[1]) - 1,
            np.sqrt(3) * np.cos(x[0]) * np.cos(x[2]) + np.sqrt(3) * np.sin(x[0]) * np.sin(x[1]) * np.sin(x[2]) - 1,
            -1 * np.sqrt(3) * np.sin(x[0]) * np.cos(x[2]) + np.sqrt(3) * np.cos(x[0]) * np.sin(x[1]) * np.sin(x[2]) -1
           ]

root1 = fsolve(func, [0 ,0 ,0])
a1, b1, c1 = root1
print(np.isclose(func(root1), [0, 0, 0]))

root2 = fsolve(func, [7*np.pi/4, 0, np.pi/4])
a2, b2, c2 = root2
print(np.isclose(func(root2), [0, 0, 0]))
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################

[ True  True  True]
[ True  True  True]


In [58]:
root2

array([5.51454805, 0.02369795, 0.61567832])

In [51]:
# root2 = [7*np.pi/4, 0, np.pi/4]
# a2, b2, c2 = root2
# x_2_obtained_case2 = rotation_from_euler_zyx(a2,b2,c2) @ x_1.T
# x_2_obtained_case2

array([0.8660254 , 0.8660254 , 1.22474487])

In [42]:
# From Section 2.2, use the function which takes Euler angles and gives Rotation matrix as output.
# Uncomment and replace `r_mat` with the name of the function. (Do NOT edit anything else)
x_2_obtained_case1 = rotation_from_euler_zyx(a1,b1,c1) @ x_1.T #TODO: replace r_mat
x_2_obtained_case2 = rotation_from_euler_zyx(a2,b2,c2) @ x_1.T #TODO: replace r_mat
test = True #TODO: Set this as True

In [43]:
# DON'T EDIT
if test == True:
    case1_test = np.isclose(x_2_obtained_case1,  np.array([1.0,1.0,1.0]))
    case2_test = np.isclose(x_2_obtained_case2,  np.array([1.0,1.0,1.0]))
    print("For case 1, it is " + str(bool(case1_test[0] and case1_test[1] and case1_test[2])) + 
          " that I could end up at (1,1,1) after rotation.")
    print("For case 2, it is " + str(bool(case2_test[0] and case2_test[1] and case2_test[2])) + 
          " that I could end up at (1,1,1) after rotation.")

For case 1, it is True that I could end up at (1,1,1) after rotation.
For case 2, it is True that I could end up at (1,1,1) after rotation.


## 2.4 Gimbal Lock visualization (Optional)

A nice visualization video for gimbal lock is [this](https://www.youtube.com/watch?v=zc8b2Jo7mno). You are about to animate a similar visualization demonstrating gimbal lock 😃.

![image.png](./misc/xyz-frame.png)

- Write a function `two_four` for the visualization of gimbal lock. Follow the below steps to get the intuition going. Use Open3D for the following.
    - Say our frame's initial position is as the above image. Now the final goal at the end of rotation is to get the $Y$ axis pointing in the direction of the vector $(x,y,z)$ that you currently see in the above image. This point is fixed in space and is NOT moving as we rotate our axis.
    - For creating that point, you could use a small sphere using `open3d.geometry.create_mesh_sphere`. You already know how to create an axis by now.
    - Following our $ZYX$ convention, first rotate your frame about $Z$ axis by an angle, say $-35^{\circ}$. Then rotate about $Y$ axis by an angle ${\beta}$ and then about $X$ by say $55^{\circ}$.
        - Are there any specific angle(s) $\beta$ using which you will **never** reach our point $(x,y,z)$ ?
            - Clue: We are specifically talking about gimbal lock here and notice the word "never".
        - Under this (these) specific angle(s) of $\beta$ & different combinations of $\alpha$ and $\gamma$, make an animation and clearly show why your $Y$ axis is unable to align in the direction of that vector $(x,y,z)$ using the animation.

            If you are unsure to simulate the animation, you could do it as follows:

            - You could first fix some $\alpha$, say $-35^{\circ}$ & an above value of $\beta$, you can now vary $\gamma$ from $-180^{\circ} \text{ to }180^{\circ}$ to simulate the animation.
            - Now fix another $\alpha$, say $45^{\circ}$ and repeat the above process. So that's 2 specific values of $\alpha$.
            - Show this for all angles of $\beta$ if there are more than 1.
            - Therefore, when the code is run, there should be a minimum of (2 $\times$ (number of values of $\beta$)) animations. 2 for values of $\alpha$, you could show it for even more if you wish to.

In [ ]:
##############################################################################
# TODO: Do tasks described in 2.4                                            #
##############################################################################
# Replace "pass" statement with your code
pass
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################

> VOILA! You have just animated the famous Gimbal lock problem. If you are curious, read about the [Apollo 11](https://en.wikipedia.org/wiki/Gimbal_lock#On_Apollo_11) Gimbal lock incident.

### Questions for 2.4 (Optional)

- Mention the value(s) of $\beta$ here: 
    * Ans: *your answer here.*
- Now that you understand gimbal lock through visualization, explain it now in matrix form: For the above values of $\beta$, what does the rotation matrix look like? Can you explain why gimbal lock occurs from the rotation matrix alone? Clue: Use sin/cos formulae. 
    * Ans: *your answer here.*
- Call the function `two_four` for the visualization of gimbal lock written above. 

In [ ]:
#uncomment the following and add input parameters if any
#two_four()